version: 2.1

jobs:

  build_server:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 code/Server.py -build  
  build_proxy:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 code/Proxy.py -build
      # - run: python3 code/MultiThreadServer.py -build
  test_server:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 code/TestServer.py    
  test_proxy:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 code/TestProxy.py    

workflows:
  build_and_test:
    jobs:
      - build_server
      - build_proxy
      - test_server:
          requires:
            - build_server
      - test_proxy:
          requires:
            - build_proxy